import { ReportedIncidents } from "@/types";

export const ReportedIncidentsData: ReportedIncidents[] = [
    {
        id: "inc001",
        title: "Unauthorized access attempt",
        description: "Multiple failed login attempts detected on admin portal.",
        status: "investigating",
        reported: "alice@example.com",
        date: "2025-05-28",
    },
    {
        id: "inc002",
        title: "Data breach",
        description: "Sensitive customer data may have been exposed.",
        status: "confirmed",
        reported: "bob@example.com",
        date: "2025-05-25",
    },
    {
        id: "inc003",
        title: "System outage",
        description: "Service downtime in region AP-SOUTHEAST-1.",
        status: "resolved",
        reported: "carol@example.com",
        date: "2025-05-22",
    },
    {
        id: "inc004",
        title: "Suspicious file upload",
        description: "A potentially malicious file was uploaded to the server.",
        status: "under review",
        reported: "dave@example.com",
        date: "2025-05-20",
    },
    {
        id: "inc005",
        title: "Phishing email reported",
        description: "Users received a fake internal email requesting credentials.",
        status: "resolved",
        reported: "eve@example.com",
        date: "2025-05-18",
    },
    {
        id: "inc006",
        title: "Firewall misconfiguration",
        description: "Open ports detected during routine audit.",
        status: "confirmed",
        reported: "frank@example.com",
        date: "2025-05-17",
    },
    {
        id: "inc007",
        title: "Unencrypted data transfer",
        description: "Detected transmission of sensitive data over HTTP.",
        status: "investigating",
        reported: "grace@example.com",
        date: "2025-05-15",
    },
];
